# Generated by Django 3.0.3 on 2020-02-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genetica', models.CharField(max_length=200)),
                ('puntuacion', models.IntegerField(default=0)),
                ('fecha', models.DateField(verbose_name='dia plantada')),
            ],
        ),
    ]
